name: Project idea template
description: For creating a new project(as an issue) following the design
title: "Project Idea"
body:
  - type: textarea
    attributes:
      label: Project description
      description: A short description here, describing the idea.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Introduction
      description: A small introduction
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why
      description: Here you need to explain, what is the need of this project.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Describe the project the best you can. Give any background information or link to resources that are necessary to understand the problem it is intended to solve. The more you elaborate on your idea, the easier it is to accomplish.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Technology
      description: Write what technology is relevant. What language, what platform, any particular library/framework/existing project it is based on?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
      ## Complexity and required time
      <!--[Please only tick off one box in each category by changing `[ ]` to `[x]`. The labels on the project will then be updated by the maintainers as soon as possible.-->
  - type: checkboxes
    id: complexity
    attributes:
      label: Complexity
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
        - label: Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
        - label: Advanced - The project requires the user to have a good understanding of all components of the project to contribute
# 
# ### Required time (ETA)
# 
# - [ ] Little work - A couple of days
# - [ ] Medium work - A week or two
# - [ ] Much work - The project will take more than a couple of weeks and serious planning is required
# 
# ### Categories
# 
# - [ ] Mobile app
# - [ ] IoT
# - [ ] Web app
# - [ ] Frontend/UI
# - [ ] AI/ML
# - [ ] APIs/Backend
# - [ ] Voice Assistant
# - [ ] Developer Tooling
# - [ ] Extension/Plugin/Add-On
# - [ ] Design/UX
# - [ ] AR/VR
# - [ ] Bots
# - [ ] Security
# - [ ] Blockchain
# - [ ] Futuristic Tech/Something Unique
