name: Project idea template
description: For creating a new project(as an issue) following the design
title: "Project Idea"
body:
  - type: input
    attributes:
      label: Introduction
      description: Explain in one line what the project is about
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why
      description: Here you need to explain, what is the need of this project.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Describe the project the best you can. Give any background information or link to resources that are necessary to understand the problem it is intended to solve. The more you elaborate on your idea, the easier it is to accomplish.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant Technology
      description: Write what technology is relevant. What language, what platform, any particular library/framework/existing project it is based on?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Complexity and required time
        Please only tick off one box in each category by changing `[ ]` to `[x]`. The labels on the project will then be updated by the maintainers as soon as possible.
  - type: checkboxes
    id: complexity
    attributes:
      label: Complexity
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: Little work - A couple of days
        - label: Medium work - A week or two
        - label: Much work - The project will take more than a couple of weeks and serious planning is required
  - type: checkboxes
    id: categories
    attributes:
      label: Categories
      options:
        - label: Mobile app
        - label: IoT
        - label: Web app
        - label: Frontend/UI
        - label: AI/ML
        - label: APIs/Backend
        - label: Voice Assistant
        - label: Developer Tooling
        - label: Extension/Plugin/Add-On
        - label: Design/UX
        - label: AR/VR
        - label: Bots
        - label: Security
        - label: Blockchain
        - label: Futuristic Tech/Something Unique
